shift: 168
multi_step_forecast: 24
percentage_train: 0.6
percentage_validation: 0.2
scaler_inputs: standard
scaler_targets: minmax

batch_size: 32
size_input: 168
size_output: 24
size_hidden: 72
num_layers_lstm: 2
num_layers_linear: [64, 128, 256, 128, 64]
activation_function: relu

num_epochs: 1000
learning_rate: 0.001
optimizer: adam
criterion: mse