shift: 24
multi_step_forecast: 24
percentage_train: 0.6
percentage_validation: 0.2
scaler_inputs: standard
scaler_targets: minmax

size_input: 24
size_output: 24
size_hidden: 72
num_layers_lstm: 2
num_layers_linear: [128, 64]
activation_function: relu

num_epochs: 1000
learning_rate: 0.001
optimizer: adam
criterion: mse