shift: 24
pertentage_train: 0.7
scaler_inputs: standard
scaler_targets: minmax

size_output: 1
size_input: 24
size_hidden: 12
num_layers: 1

num_epochs: 100
learning_rate: 0.001
optimizer: adam
criterion: mse